version: '3.8'

services:
  discovery-server:
    image: microservices-app-discovery-server
    container_name: discovery-server
    ports:
      - "8762:8762"

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_db
    ports:
      - "3308:3306"

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"

  order-service:
    image: microservices-app-order-service
    container_name: order-service
    depends_on:
      - discovery-server
      - mysql-order
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    image: microservices-app-user-service
    container_name: user-service
    depends_on:
      - discovery-server
      - mysql-user
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: microservices-app-api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-server
      - user-service
      - order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
