server:
  port: 8762
  address: 0.0.0.0

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 0.0.0.0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/

spring:
  application:
    name: discovery-server