server:
  port: 8762

eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-server:8762/eureka/

spring:
  application:
    name: discovery-server